Repository BalticAmadeus/ProBro, pull requests merged in 2024-10, with the labels that each got.

#585 Update button disabled for read only db
  src/view/app/Query/Update/update.tsx
Labels: bug

#592 Fix for bad query error bug
  src/view/app/Query/query.tsx
Labels: bug

#591 Support for multiple installed OE installations
  resources/oe/scripts/oe.bat
  src/common/OpenEdgeJsonReaded.ts
  src/db/OeClient.ts
  src/extension.ts
Labels: enhancement

#589 icons appear beside db in extension dev
  package-lock.json
  package.json
  webpack.config.js
Labels: dev improvement
